# nome da pipeline
name: Run Basic Testes

# em que momento será executada
on:
  pull_request: 
    branches: [master]


jobs:
  # o que vai ser feito nessa pipeline
  # só teremos um job: rodar os testes
  cypress-run:
    # maquina que será executada
    runs-on: ubuntu-latest 

    # passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone dos projetos
        uses: actions/checkout@v3

      # exemplo de execução no terminal
      - name: instalar dependencias do projeto
        uses: echo Carla Oliveira

      # execução e configuração do projeto
      - name: Run testes
        uses: cypress-io/github-actions@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}